
name: React Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    
    - name: Install Node.js
      uses: actions/checkout@v2-beta
      with:
        node-version: 12
        
    - uses: borales/actions-yarn@v2.0.0
      with:
          cmd: install # will run `yarn install` command
    
    - name: Build React App
      run: yarn build
        
    - name: Install Surge
      run: npm install --global surge
      
    - name: Deploy To Surge
      run: surge ./build react-application-by-gopaldas.surge.sh --token ${{secrets.SURGE_TOKEN}}
    
